version: '3.8'

services:
  moneyplanet-ai:
    build:
      context: .
      dockerfile: Dockerfile
    image: moneyplanet-fastapi-server:latest
    restart: always
    container_name: moneyplanet-fastapi-server
    depends_on:
      - ai-db
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - .:/app
    env_file:
      - .env

  ai-db:
    image: postgres:13
    container_name: moneyplanet-fastapi-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - app-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ai_db

networks:
  app-network:
    external: true

volumes:
  postgresql_data: