"""init

Revision ID: dae1b68ff04f
Revises: 
Create Date: 2025-05-12 19:15:07.178180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae1b68ff04f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Decision',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('planet', sa.String(length=26), nullable=False),
    sa.Column('gender', sa.String(length=26), nullable=False),
    sa.Column('prefer', sa.String(length=26), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(length=26), nullable=False),
    sa.Column('tx_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=26), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('abc', sa.String(length=5), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('feedback', sa.String(length=255), nullable=True),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Decision'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Decision')
    # ### end Alembic commands ###
